# Generated by Django 4.2.17 on 2025-01-17 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_remove_profile_headline_profile_short_intro_and_more'),
        ('artworks', '0002_artworks_featured_image_artworks_listing_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworks',
            name='profile_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artists.profile'),
        ),
    ]
