# Generated by Django 4.2.17 on 2025-01-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_artworks_profile_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artworks',
            options={'ordering': ['-created']},
        ),
    ]
